### ISSUE TITLE
Async methods

### ISSUE THREAD

**Issue by nadjibus** [recombee/net-api-client#1]
It's very useful, especially for network related tasks (like Recombee API) to use async methods rather than sync ones.

**Comment by nadjibus** [comment]
Well I forked the project and added support for Async, supplying an HttpClient instance, and fixed bugs (you have a big bug that [creates a new HttpClient instance each request](https://github.com/recombee/net-api-client/blob/4cb076b9204c84e2c3db9353e0cf503cde48fa3e/Src/Recombee.ApiClient/RecombeeClient.cs#L236)). Feel free to integrate my changes in a future update.

**Comment by OndraFiedler** [comment]
Thanks for making the effort! Can you please point out other fixed bugs? It will be helpful if we decide to merge your fork.

Regarding creating the HttpClient instance, it is somehow intentional as each request should have different timeout, which is not very supported by HttpClient. It is not creating new instances of HttpClient as long as the requests have the same timeout.

**Comment by nadjibus** [comment]
Thank you for your reply.

For HttpClient instance, I still think that it is indeed created each request, because HttpClient default timeout is 100 seconds, and your requests are 1 second I think, so it will always be different (unless the user makes it manually 100 seconds for each request)

Also you can define a timeout by request easily without having to create a new HttpClient instance, by using HttpClient.SendAsync(HttpRequestMessage) instead of HttpClient.GetAsync/PostAsync (you can check [my implementation](https://github.com/nadjibus/net-api-client/blob/211a0cca8a5d05c17f9e1228e9e2a7016804d468/Src/Recombee.ApiClient/RecombeeClient.cs#L227))

Also in my implementation I made the default request timeout to 10 seconds. 1 was too optimistic, 60-80% of unit tests were failing due to timeouts (the remaining 20% were bad tests, didn't have the time to fix them sorry).

Your team had successful unit tests with the 1 sec timeout maybe because you are located near your servers (just guessing here...)

For other bugs, they were minor (spelling errors, unoptimized code...)

The code itself can be optimized and simplified A LOT by using generics (probably around 60-70% of the can be removed). Sorry didn't have enough time to do it, since I have to implement your awesome SDK into my project :)

**Comment by OndraFiedler** [comment]
Thank you @nadjibus for your effort regarding asynchrous send in the SDK.
The support for `SendAsync` has been added to the SDK in version 2.5.0. The implementation is partly based on your fork.
The `Send` method is kept in order to keep backward compatibility.

**Comment by nadjibus** [comment]
Congrats! thank you for the good job!
