### ISSUE TITLE
404 Error: Unknown key or database

### ISSUE THREAD

**Issue by SonnyCampbell** [Recombee/net-api-client#2]
I keep getting a 404: Unknown key or database when attempting to recreate the basic example usage of this repo.

I created a new Console Application, copy-pasted the code in Main() into my Main function, used my own db/secret credentials, and it keeps throwing a 404.

`RecombeeClient client = new RecombeeClient("anothertestdb", "c9IqbymphFR3ff3bPm5IrTo9RLhvDIFRkRz8zel0hvYTuBorvOpA5McKILURCvJ2");`

![image](https://user-images.githubusercontent.com/4961041/35333400-87179ada-0106-11e8-8d48-69737ca71725.png)

The code is literally copy-pasted (with my own key/secret as above) right out of the Basic Example, but every time it hits `client.Send(new Batch(purchases)); //Use Batch for faster processing of larger data` it throws an exception.

Am I missing something, or do I need to set up any different configuration to get it running?

**Comment by OndraFiedler** [comment]
I confirm that there is an issue with creating new databases in the system. Our technicians are working on it. Please wait until it is resolved. We are sorry for any inconvenience.

**Comment by SonnyCampbell** [comment]
No worries, thanks for letting me know so quickly. 

Is it a .NET specific issue, or is it across Recombee in general? And do you have any sort of rough estimate when it might be resolved?

**Comment by OndraFiedler** [comment]
It has been resolved just now. Thanks for reporting the issue.
