### ISSUE TITLE
Token Has Expired Error

### ISSUE THREAD

**Issue by MohammedTawfik** [recombee/net-api-client#3]
Hello All,

when i use this code to send batch of data 

const int NUM = 100;
            var userIds = Enumerable.Range(0, NUM).Select(i => string.Format("user-{0}", i));
            var itemIds = Enumerable.Range(0, NUM).Select(i => string.Format("item-{0}", i));
            // Generate some random purchases of items by users
            const double PROBABILITY_PURCHASED = 0.1;
            Random r = new Random();
            var purchases = new List<Request>();

            foreach (var userId in userIds)
            {
                purchases.AddRange(
                    itemIds.Where(_ => r.NextDouble() < PROBABILITY_PURCHASED)
                           .Select(itemId =>
                                    new AddPurchase(userId, itemId, cascadeCreate: true) // Use cascadeCreate parameter to create
                           )                                                             // the yet non-existing users and items
                );
            }
            var datetime = DateTime.Parse(DateTime.Now.ToString(), null, System.Globalization.DateTimeStyles.RoundtripKind);
            recombeeClient.Send(new Batch(purchases),);

i got this error 

{"statusCode":401, "error":"Token has expired (Current time: 1521061040 or 2018-03-14 20:57:20 UTC, you are -121s off)"}

**Comment by OndraFiedler** [comment]
It seems like the time at your machine is wrong. Recombee uses HMAC mechanism to assure authenticity of incoming requests. The clock on the machine where you sign the requests must be properly synchronized, there is only 10 seconds tolerance, but you are 120 seconds ahead and therefore requests doesn’t pass authentication.
 
Can you please fix it? I suggest using some time synchronization tool, such as ntpd.

**Comment by MohammedTawfik** [comment]
it is worked thanks alot

**Comment by MohammedTawfik** [comment]
Sorry but i have another question how i can get recommendations for new user registered on my site and have no interactions ?

**Comment by OndraFiedler** [comment]
> Sorry but i have another question how i can get recommendations for new user registered on my site and have no interactions ?

You can use `cascadeCreate` parameter of the recommendation request (https://docs.recombee.com/api.html#recommend-items-to-user). It will create the user if the user doesn't exist yet.
